Innorovation.SiteSkeleton/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;

namespace Innorovation.SiteSkeleton.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }
    }
}

Innorovation.SiteSkeleton/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using Innorovation.SiteSkeleton.Areas.HelpPage.Models;

namespace Innorovation.SiteSkeleton.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

Innorovation.SiteSkeleton/Controllers/ApiHelpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Innorovation.SiteSkeleton.Controllers
{
    public class ApiHelpController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

Innorovation.SiteSkeleton/Controllers/HomeController.cs
using Innorovation.ControlCode.Razor;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Innorovation.SiteSkeleton.Controllers
{
    public class HomeController : Controller
    {
        static ViewGenerator generator = new ViewGenerator();
        static HomeController()
        {
            generator.AddControls(new Dictionary<string, string>
            {
                {"span","<span>@Model.Name</span>"}
            });
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ControlDefinition()
        {
            return View();
        }

        public ActionResult ViewRendering()
        {
            return View();
        }

        public ActionResult RenderMarkupHtml(MarkupData data)
        {
            var markup = data.Markup;
            generator.AddControl(data.Name, data.Markup);
            var json = JObject.Parse(data.Model??"{}");
            var result = generator.RenderView(data.Name, json);
            return Content(result);
        }
    }

    public class MarkupData
    {
        public string Name { get; set; }
        public string Markup { get; set; }
        public string Model { get; set; }
    }
}

Innorovation.SiteSkeleton/Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Innorovation.SiteSkeleton.Controllers
{
    public class ValuesController : ApiController
    {
        // GET api/values
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/values/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/values
        public void Post([FromBody]string value)
        {
        }

        // PUT api/values/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        public void Delete(int id)
        {
        }
    }
}

Innorovation.SiteSkeleton/Views/ApiHelp/Index.cshtml
@{
    Layout = "";
}
<div id="body">
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>Welcome to ASP.NET Web API!</h1>
                <h2>Modify the code in this template to jump-start your ASP.NET Web API development.</h2>
            </hgroup>
            <p>
                ASP.NET Web API allows you to expose your applications, data and services to the
                web directly over HTTP.
            </p>
            <p>
                To learn more about ASP.NET Web API visit the
                <a href="http://go.microsoft.com/fwlink/?LinkID=238195" title="ASP.NET Web API Website">ASP.NET Web API Website</a>.
                The page features <mark>videos, tutorials, and samples</mark> to help you get the most from ASP.NET Web API.
                If you have any questions about ASP.NET Web API, visit
                <a href="http://go.microsoft.com/fwlink/?LinkID=238196" title="ASP.NET Web API Forum">our forums</a>.
            </p>
        </div>
    </section>
    <section class="content-wrapper main-content clear-fix">
        <h3>We suggest the following steps:</h3>
        <ol class="round">
            <li class="one">
                <h5>Getting Started</h5>
                ASP.NET Web API is a framework that makes it easy to build HTTP services that reach
                a broad range of clients, including browsers and mobile devices. ASP.NET Web API
                is an ideal platform for building RESTful applications on the .NET Framework.
                <a href="http://go.microsoft.com/fwlink/?LinkId=245160">Learn more…</a>
            </li>

            <li class="two">
                <h5>Add NuGet packages and jump-start your coding</h5>
                NuGet makes it easy to install and update free libraries and tools.
                <a href="http://go.microsoft.com/fwlink/?LinkId=245161">Learn more…</a>
            </li>
            <li class="three">
                <h5>Find Web Hosting</h5>
                You can easily find a web hosting company that offers the right mix of features
                and price for your applications.
                <a href="http://go.microsoft.com/fwlink/?LinkId=245164">Learn more…</a>
            </li>
        </ol>
    </section>
</div>

Innorovation.SiteSkeleton/Views/Home/ControlDefinition.cshtml
@{
    ViewBag.Title = "ControlDefinition";
}
<div class="container">
    <div class="page-header">
        <h2>Control Definition</h2>
    </div>
    <div class="container">
        <div class="col-md-4">
            <ul class="nav nav-tabs">
                <li><a href="#tbpgMarkup" data-toggle="tab">Markup</a></li>
                <li><a href="#tbpgModel" data-toggle="tab">Model</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane" id="tbpgMarkup">
                    <label>Name:</label>
                    <input type="text" id="txtName" value="" />
                    <label>Enter control markup:</label>
                    <div>
                        <textarea id="txtMarkup" rows="10"></textarea>
                    </div>
                </div>
                <div class="tab-pane" id="tbpgModel">
                    <label>Enter model json:</label>
                    <div>
                        <textarea id="txtModel" rows="10"></textarea>
                    </div>
                </div>
            </div>
            <button id="btnRender" class="btn" data-inv-action-url="@Url.Action("RenderMarkupHtml", "Home")">Render</button>

            <div class="col-md-4">
                <div id="controlLayout">
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script type="text/javascript">
        var actionUrl = $('#btnRender').attr('data-inv-action-url');
        $('#btnRender').click(function () {
            var name = $('#txtName').val();
            var markup = $('#txtMarkup').val();
            var model = $('#txtModel').val();
            $.ajax({
                type: 'post',
                url: actionUrl,
                data: { 'markup': markup, 'name': name, 'model': model },
                success: function (response, textStatus, xhr) {
                    var data = response;
                    var markupGenerated = $(data);
                    $('#controlLayout').empty();
                    $('#controlLayout').append(markupGenerated);
                },
                error: function (xhr, textStatus, error) {
                    console.log(xhr, textStatus, error);
                },
                dataType: 'html'
            });
        });
    </script>
}

Innorovation.SiteSkeleton/Views/Home/Index.cshtml
<div class="container">
    <div class="page-header">
        <h1>Landing page</h1>
    </div>
    <div class="container row">
        <div class="col-md-3">
            <div>
                @Html.ActionLink("Control definition", "ControlDefinition", "Home")
            </div>
            <div>
                @Html.ActionLink("View Rendering", "ViewRendering", "Home")
            </div>
        </div>
        <div class="col-md-9">
            this is regular stuff
        </div>
    </div>
</div>

Innorovation.SiteSkeleton/Views/Home/ViewRendering.cshtml
@{
    ViewBag.Title = "ViewRendering";
}

<h2>ViewRendering</h2>

Innorovation.SiteSkeleton/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
</head>
<body>
    @RenderBody()    
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    <script src="~/Scripts/bootstrap.js"></script>
    @RenderSection("scripts",false)
</body>
</html>

Innorovation.SiteSkeleton/Views/Shared/_LayoutApi.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">
                    <a href="~/">ASP.NET Web API</a></p>
            </div>
            <div class="float-right">
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>